[context]
host = "0.0.0.0"
port = "9999"
debug = true
docker = true

[database]
username = "juan"
password = "juan"
schema = "pagarme"

[database_test]
username = "juan"
password = "juan"
schema = "pagarme_test"

