[context]
host = "0.0.0.0"
port = "9999"
debug = true
docker = false

[database_test]
host = "localhost"
port = "3306"
username = "juan"
password = "juan"
schema = "pagarme_test"

[database]
host = "localhost"
port = "3306"
username = "juan"
password = "juan"
schema = "pagarme"
