@startuml
title createTx
skinparam responseMessageBelowArrow true
controller -> service : TransactionsService.ValidateTx(*models.Transaction)
controller -> service : ClientsService.Fetch(*models.Client)
service -> db : pg_client_fetch({id_client})
alt client doesn't exists

    controller -> service: ClientsService.Create(*models.Client)
    service -> db : pg_client_create({Client})

end

controller -> service : CardsService.FetchByNumber(Card.Number)
service -> db : pg_card_fetch_by_number({card_number})

alt card doesn't exists

    controller -> service: CardService.Create(*models.Card)
    service -> db : pg_card_create({Card})

end

alt card is not registered for that client

    controller -> service: ClientsService.RegisterCard(idCard, idClient)
    service -> db : pg_client_register_card({id_card, id_client})

end

controller -> service : TransactionsService.Create(*models.Transaction)
service -> db : pg_transactions_create({Transaction})

@enduml